/******************************************************************************
*
*	bgm_error.c -
*		Implementation of BGM's error handling system.
*
*	In BGM, an error message is a simple string that supplies basic information
*	about an error, usually the one that just occured.
*	An error _report_, however, is a highly-verbose piece of output that gives
*	as much info about the last error that occured (whether or not it JUST
*	occured) as possible.
*	The latest error report that BGM has given will be stored in a log file in
*	the program's working directory. It will contain the text of the last error
*	message plus a lot more information.
*
******************************************************************************/

#include "bgm.h"

/******************************************************************************
 * Error Report Format String - 
 *	This is the format string used to generate the content of the error report
 *	log file.
 *****************************************************************************/
const char bgm_errorReportStr[] =

"This file was automatically generated by BGM.DLL when the last error\n\
occured. If you don't want this file to be generated you can deactivate it\n\
by calling bgm_ErrorReport(false) in your GML code.\n\
\n\
--- BGM Error Report ---\n\
ERROR DATE: %s\n\
SRC FILE:   %s\n\
LINE NO:    %i\n\
MESSAGE:    \"%s - %s\"\n\
VERSION:    %s\n\
BUILD DATE: %s\n\
--- End of Report ------";


/******************************************************************************
 * Globals
 *****************************************************************************/

char	bgm_errorContext[128]; // Holds a small description of the context in
                               // which any errors will occur. This string will
							   // be prepended to all error messages outputed.
char	bgm_errorMsg[1024]; // Contains a description of the last error that
                            // occured.
                            
/******************************************************************************
 * Function implementations
 *****************************************************************************/

/*	bgm_Error() -
		Returns the last error message and clears the error string. */
DLL_FUNC
GM_STRING bgm_Error()
{
	sprintf(bgm_tmpStr, "%s - %s", bgm_errorContext, bgm_errorMsg);
	sprintf(bgm_errorMsg,"");
	return bgm_tmpStr;
}

/*	bgm_SetReportErrors() -
		Sets the value of bgm_config.reportErrors */
DLL_FUNC
GM_REAL bgm_SetReportErrors(GM_REAL val)
{
	bgm_config.reportErrors = (BOOL)val;
	return TRUE;
}

/*	_bgm_ErrorReport() -
		Internal function to report an error. Don't call this explicitly;
		instead, use the macro BGM_ERROR() which writes a call to this
		function. */
void _bgm_ErrorReport(char *file, int line)
{
	FILE	*f;
	time_t	theTime;
	struct	tm *cal;	// NOTE: the 'struct' before tm MUST be used in plain C
	char	date[100];
	
	DOUT ("ERROR: %s - %s\n", bgm_errorContext, bgm_errorMsg);
	
	// Quit now if error reporting is off
	if (!bgm_config.reportErrors)
		return;
	
	// Get a date string for today
	theTime = time(NULL);
	if (theTime != -1) {
		cal = gmtime(&theTime);
		if (cal)
			sprintf(date, "%i/%i/%i", cal->tm_mon+1, cal->tm_mday, 
			  cal->tm_year+1900);
		else
			strcpy(date, "unavailable");
	}
	else
		strcpy(date, "unavailable");			
	
	// Write the report
	f = fopen("bgm_error.log","w");
	fprintf(f, bgm_errorReportStr,
	           date,
			   file,
			   line,
			   bgm_errorContext, bgm_errorMsg,
			   BGM_INFO_VERSION,
			   __DATE__);
	fclose(f);
}
